#! /bin/sh

bspc monitor DVI-I-1 -n 0 -d alpha beta
bspc monitor DVI-I-2 -n 1 -d gamma delta

bspc config border_width        2
bspc config window_gap          12
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding		14

bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
