#! /bin/sh

bspc monitor DVI-I-1 -n 0 -d alpha beta gamma
bspc monitor DVI-I-2 -n 1 -d delta epsilon zeta

bspc config border_width        2
bspc config focused_border_color #005F87
bspc config window_gap          12
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding		14
bspc config -m 0 left_padding 40

bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
